### ISSUE TITLE
panic trying to generate bindings for Harfbuzz

### ISSUE THREAD

**Issue by deepakjois** [xlab/cgogen#2]
I was trying out cgogen to see if I could generate bindings for Harfbuzz:
https://github.com/deepakjois/harfbuzz-go

I get a panic, and I am not sure what could be wrong. I just copied the headers of the project and wrote a simple .yml file.

```

  [36mprocessing harfbuzz.yml[m ⠋[WARN] PKG_CONFIG_PATH is not set
panic: internal error: uint8

goroutine 1 [running]:
panic(0x2f3040, 0xc42037f520)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cznic/cc.(*Expression).eval(0xc4204a7140, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1110 +0x90d9
github.com/cznic/cc.(*ExpressionList).eval(0xc4204b9c20, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1711 +0x5b
github.com/cznic/cc.(*Expression).eval(0xc4204a7200, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:635 +0xf23
github.com/cznic/cc.(*Model).binOp(0x537360, 0xc4203663c0, 0x4f82c0, 0xc4204a7200, 0x4f82c0, 0xc4204a7740, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/deepak/.gopath/src/github.com/cznic/cc/model.go:1027 +0x56
github.com/cznic/cc.(*Expression).eval(0xc4204a7800, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1429 +0xed34
github.com/cznic/cc.(*Model).binOp(0x537360, 0xc4203663c0, 0x4f82c0, 0xc4204a7800, 0x4f82c0, 0xc4204a7d40, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/deepak/.gopath/src/github.com/cznic/cc/model.go:1027 +0x56
github.com/cznic/cc.(*Expression).eval(0xc4204a7e00, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1429 +0xed34
github.com/cznic/cc.(*Model).binOp(0x537360, 0xc4203663c0, 0x4f82c0, 0xc4204a7e00, 0x4f82c0, 0xc4204e8180, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/deepak/.gopath/src/github.com/cznic/cc/model.go:1027 +0x56
github.com/cznic/cc.(*Expression).eval(0xc4204e8240, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1429 +0xed34
github.com/cznic/cc.(*ExpressionList).eval(0xc4204b9ef0, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1711 +0x5b
github.com/cznic/cc.(*Expression).eval(0xc4204e8300, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:635 +0xf23
github.com/cznic/cc.(*Expression).eval(0xc4204e83c0, 0xc4203663c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:821 +0x317d
github.com/cznic/cc.(*ExpressionList).eval(0xc4204a2d20, 0xc4203663c0, 0x24120000e028, 0x35, 0x2e0540, 0xc42037f218)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1711 +0x5b
github.com/cznic/cc.(*Expression).eval(0xc4204e8480, 0xc4203663c0, 0x4c, 0xc4201c0348, 0xc420019000, 0xc42037f200)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:635 +0xf23
github.com/cznic/cc.yyParse(0x4f8300, 0xc4203663c0, 0xc420015920)
	/Users/deepak/.gopath/src/github.com/cznic/cc/parser.go:3200 +0x5cc9
github.com/cznic/cc.Parse(0xc420212dc0, 0x2ba, 0xc42000f6f0, 0x1, 0x1, 0x537360, 0xc42022fab8, 0x2, 0x2, 0xc420097a78, ...)
	/Users/deepak/.gopath/src/github.com/cznic/cc/cc.go:506 +0x753
github.com/xlab/cgogen/parser.ParseWith(0xc42006f080, 0xc42000b740, 0x2, 0x2)
	/Users/deepak/.gopath/src/github.com/xlab/cgogen/parser/parser.go:80 +0x109c
main.NewCGOGen(0x7fff5fbff977, 0xc, 0x0, 0x0, 0xc42000f1d0, 0xc420015200, 0x0)
	/Users/deepak/.gopath/src/github.com/xlab/cgogen/cgogen.go:79 +0x2f0
main.main()
	/Users/deepak/.gopath/src/github.com/xlab/cgogen/main.go:80 +0x24d
```

**Comment by cznic** [comment]
@deepakjois  Please try with https://github.com/cznic/cc/commit/3437dda41511ae71897c15bc847cd0d0cb4bf5a1 .

**Comment by xlab** [comment]
@cznic still another missing case on `case 31: // Expression "<<" Expression`

**Comment by xlab** [comment]
@deepakjois after the above is fixed you'll be free to go

```
$ cgogen harfbuzz.yml
  processing harfbuzz.yml done.
```

**Comment by deepakjois** [comment]
Sidenote: I just realised I committed wrongly to Git. Fixed now.

However a panic is still happening. @cznic Looking at your code, you seem to have added a case for `uint8` _after_ the line that panics

```

  [36mprocessing harfbuzz.yml[m ⠋[WARN] PKG_CONFIG_PATH is not set
panic: internal error: uint8

goroutine 1 [running]:
panic(0x2f3360, 0xc42000fa00)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cznic/cc.(*Expression).eval(0xc4203d6e40, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1110 +0x90da
github.com/cznic/cc.(*ExpressionList).eval(0xc4203a2d70, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1725 +0x5b
github.com/cznic/cc.(*Expression).eval(0xc4203d6f00, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:635 +0xf23
github.com/cznic/cc.(*Model).binOp(0x537360, 0xc4203883c0, 0x4f82c0, 0xc4203d6f00, 0x4f82c0, 0xc4203d7440, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/deepak/.gopath/src/github.com/cznic/cc/model.go:1027 +0x56
github.com/cznic/cc.(*Expression).eval(0xc4203d7500, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1443 +0xf04d
github.com/cznic/cc.(*Model).binOp(0x537360, 0xc4203883c0, 0x4f82c0, 0xc4203d7500, 0x4f82c0, 0xc4203d7a40, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/deepak/.gopath/src/github.com/cznic/cc/model.go:1027 +0x56
github.com/cznic/cc.(*Expression).eval(0xc4203d7b00, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1443 +0xf04d
github.com/cznic/cc.(*Model).binOp(0x537360, 0xc4203883c0, 0x4f82c0, 0xc4203d7b00, 0x4f82c0, 0xc4203d7e00, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/deepak/.gopath/src/github.com/cznic/cc/model.go:1027 +0x56
github.com/cznic/cc.(*Expression).eval(0xc4203d7ec0, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1443 +0xf04d
github.com/cznic/cc.(*ExpressionList).eval(0xc4203a3040, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1725 +0x5b
github.com/cznic/cc.(*Expression).eval(0xc420276000, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:635 +0xf23
github.com/cznic/cc.(*Expression).eval(0xc4202760c0, 0xc4203883c0, 0x0, 0x0, 0x0, 0x0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:821 +0x317d
github.com/cznic/cc.(*ExpressionList).eval(0xc4203a3090, 0xc4203883c0, 0x24120000e028, 0x35, 0x2e0860, 0xc42000f720)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:1725 +0x5b
github.com/cznic/cc.(*Expression).eval(0xc420276180, 0xc4203883c0, 0x4c, 0xc4201ecad8, 0xc4201c6c00, 0xc42000f700)
	/Users/deepak/.gopath/src/github.com/cznic/cc/ast2.go:635 +0xf23
github.com/cznic/cc.yyParse(0x4f8300, 0xc4203883c0, 0xc42008b6b0)
	/Users/deepak/.gopath/src/github.com/cznic/cc/parser.go:3200 +0x5cc9
github.com/cznic/cc.Parse(0xc42023adc0, 0x2ba, 0xc420087680, 0x1, 0x1, 0x537360, 0xc4204c9ab8, 0x2, 0x2, 0xc4200a5a78, ...)
	/Users/deepak/.gopath/src/github.com/cznic/cc/cc.go:506 +0x753
github.com/xlab/cgogen/parser.ParseWith(0xc420384840, 0xc420095ba0, 0x2, 0x2)
	/Users/deepak/.gopath/src/github.com/xlab/cgogen/parser/parser.go:80 +0x109c
main.NewCGOGen(0x7fff5fbff977, 0xc, 0x0, 0x0, 0xc420086f00, 0xc42008af90, 0x0)
	/Users/deepak/.gopath/src/github.com/xlab/cgogen/cgogen.go:79 +0x2f0
main.main()
	/Users/deepak/.gopath/src/github.com/xlab/cgogen/main.go:80 +0x24d

```

**Comment by deepakjois** [comment]
Oh sorry, that’s exactly what @xlab  said.

Ok I am going to wait for that.

**Comment by cznic** [comment]
@deepakjois I suggest to link directly to the combination of commit/file/line. [For example](https://github.com/cznic/cc/blob/24f4bbb3da3ad4c7511ed896a684d1b480fe1841/ast2.go#L1029). That eliminates the common situation when the stack trace is from a different commit than I think it is ;-)

Are there still panics with [latest](https://github.com/cznic/cc/commit/24f4bbb3da3ad4c7511ed896a684d1b480fe1841) commit?

**Comment by deepakjois** [comment]
Ok that works. But I have other problems. I will file another issue for that

**Comment by cznic** [comment]
OK, thanks for your help :+1:
